<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    public function payable(){
        return $this->morphTo();
    }

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function save(array $options = [])
    {
        if(!$this->ocr) {
            $this->ocr = $this->generateOCR();
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function generateOCR($offset = 0){
        $ocr='';
        if($this->user){
            $ocr.= substr($this->user->personal_number,0,-4);
        }
        $ocr.=date('m');
        if($offset)
        {
            $ocr.=$offset;
        }

        if(\App\Payment::where('ocr', $ocr)->count())
            return $this->generateOCR($offset+1);
        return $ocr;
    }
}
